version: '2.1'
services:
  database:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "pass"
      POSTGRES_DB: "ostock_test"
    volumes:
        - ./init.sql:/docker-entrypoint-initdb.d/1-init.sql
        - ./data.sql:/docker-entrypoint-initdb.d/2-data.sql
    networks:
      backend:
        aliases:
          - "database"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
  configserver:
    image: ostock/configserver:0.0.1-SNAPSHOT
    ports:
       - "8089:8089"
    environment:
      SERVER_PORT: 8089
      ENCRYPT_KEY: "fje83Ki8403Iod87dne7Yjsl3THueh48jfuO9j4U2hf64Lo"
    networks:
      backend:
        aliases:
          - "configserver"
    # healthcheck:
    #   test: ["CMD", "curl", "-f", "http://configserver:8089/licensing-service/default"]  # Use the correct health endpoint
    #   interval: 15s
    #   retries: 5
    #   start_period: 60s
    #   timeout: 5s
  # licensingservice:
  #   image: ostock/licensing-service:0.0.2-SNAPSHOT
  #   environment:
  #     SPRING_PROFILES_ACTIVE: "test"  # Correctly sets the active profile to 'test'
  #     SPRING_CLOUD_CONFIG_URI: "http://configserver:8089"  # Correct config server URI
  #     SPRING_CLOUD_CONFIG_PORT: "8089"  # Optional if you need to override the default port (usually not needed if correct URI is set)
  #     DATABASESERVER_PORT: "5432"  # You can keep other environment variables as needed
  #     ENCRYPT_KEY: "IMSYMMETRIC"
  #   depends_on:
  #     database:
  #       condition: service_healthy
  #     configserver:
  #       condition: service_started
  #   ports:
  #     - "8080:8080"
  #   networks:
  #     - backend

  userservice:
    image: ostock/user-service:0.0.1-SNAPSHOT
    environment:
      SPRING_PROFILES_ACTIVE: "test"  # Correctly sets the active profile to 'test'
      SPRING_CLOUD_CONFIG_URI: "http://configserver:8089"  # Correct config server URI
      SPRING_CLOUD_CONFIG_PORT: "8089"  # Optional if you need to override the default port (usually not needed if correct URI is set)
      DATABASESERVER_PORT: "5432"  # You can keep other environment variables as needed
      ENCRYPT_KEY: "IMSYMMETRIC"
    depends_on:
      database:
        condition: service_healthy
      configserver:
        condition: service_started
    ports:
      - "8080:8080"
    networks:
      - backend

networks:
  backend:
    driver: bridge